services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - app_net
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - app_net
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 10

  cadastro-service:
    build: ./cadastro-service
    networks:
      - app_net
    environment:
      - MONGO_URI=mongodb://mongo:27017/veiculos
      - MESSAGE_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3001
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3001:3001"

  listagem-service:
    build: ./listagem-service
    networks:
      - app_net
    environment:
      - MONGO_URI=mongodb://mongo:27017/veiculos
      - MESSAGE_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3002
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3002:3002"

volumes:
  rabbitmq_data:

networks:
  app_net:
    driver: bridge
    name: vehicle_app_network
